"""Nightly version string: Nightly-0.{commits}-{tip}.

Source checkouts resolve from local git (no network). Portable builds use a
bake file stamped at package time from the same local git data.
"""

from __future__ import annotations

import os
import re
import subprocess
import sys
from pathlib import Path

# Last-resort when neither full git history nor a bake file is available.
FALLBACK_VERSION = "Nightly-0.0-unknown"

_VERSION_RE = re.compile(r"^Nightly-0\.\d+-[0-9a-f]+$")
_BAKE_PATH = Path(__file__).resolve().parent / "_version_bake.py"


def format_version(commit_count: int, tip: str) -> str:
    count = max(0, int(commit_count))
    short = str(tip).strip().lower()
    if not re.fullmatch(r"[0-9a-f]+", short):
        short = "unknown"
    return f"Nightly-0.{count}-{short}"


def _git(args: list[str], *, cwd: Path) -> str | None:
    try:
        completed = subprocess.run(
            ["git", *args],
            cwd=str(cwd),
            check=False,
            capture_output=True,
            text=True,
        )
    except OSError:
        return None
    if completed.returncode != 0:
        return None
    return completed.stdout.strip()


def _repo_root() -> Path | None:
    """Prefer PROJECT_ROOT when it is a git work tree; else walk from this file."""
    candidates: list[Path] = []
    try:
        from .config import PROJECT_ROOT

        candidates.append(Path(PROJECT_ROOT))
    except Exception:
        pass
    candidates.append(Path(__file__).resolve().parents[2])

    seen: set[Path] = set()
    for start in candidates:
        try:
            cur = start.resolve()
        except OSError:
            continue
        for path in (cur, *cur.parents):
            if path in seen:
                continue
            seen.add(path)
            if (path / ".git").exists():
                return path
    return None


def _git_is_shallow(repo: Path) -> bool:
    value = _git(["rev-parse", "--is-shallow-repository"], cwd=repo)
    return (value or "").lower() == "true"


def read_git_version(repo: Path | None = None) -> str | None:
    """Return Nightly-0.{n}-{tip} from a full local clone, else None."""
    root = repo or _repo_root()
    if root is None:
        return None
    if _git_is_shallow(root):
        # Shallow history lies about commit count — refuse rather than mislabel.
        return None
    count_text = _git(["rev-list", "--count", "HEAD"], cwd=root)
    tip = _git(["rev-parse", "--short=7", "HEAD"], cwd=root)
    if count_text is None or tip is None:
        return None
    try:
        count = int(count_text)
    except ValueError:
        return None
    return format_version(count, tip)


def read_baked_version() -> str | None:
    try:
        from . import _version_bake
    except ImportError:
        return None
    value = str(getattr(_version_bake, "VERSION", "") or "").strip()
    if not value or not _VERSION_RE.fullmatch(value):
        return None
    return value


def write_bake_file(version: str, *, path: Path | None = None) -> Path:
    if not _VERSION_RE.fullmatch(version):
        raise ValueError(f"Refusing to bake invalid version: {version!r}")
    target = path or _BAKE_PATH
    target.write_text(
        "# Auto-generated by python -m farever_atlas.versioning --stamp\n"
        "# Do not edit or commit.\n"
        f'VERSION = "{version}"\n',
        encoding="utf-8",
    )
    return target


def stamp_bake_file(*, path: Path | None = None) -> str:
    """Stamp bake file from local full git history. No network."""
    version = read_git_version()
    if version is None:
        root = _repo_root()
        if root is not None and _git_is_shallow(root):
            raise SystemExit(
                "Refusing to stamp version from a shallow git clone. "
                "Use a full history checkout (fetch-depth: 0)."
            )
        raise SystemExit(
            "Cannot stamp version: local git history unavailable."
        )
    write_bake_file(version, path=path)
    return version


def resolve_version() -> str:
    """Resolve display version without network access.

    Order:
    1. FAREVER_ATLAS_VERSION env override (tests / explicit bake)
    2. Live local git when history is complete (source checkouts)
    3. Bake file (portable exe / stamped builds)
    4. Fallback
    """
    override = str(os.environ.get("FAREVER_ATLAS_VERSION", "") or "").strip()
    if override:
        return override

    frozen = bool(getattr(sys, "frozen", False))
    if not frozen:
        live = read_git_version()
        if live is not None:
            return live

    baked = read_baked_version()
    if baked is not None:
        return baked

    # Frozen builds must ship a bake; keep fallback only as a last resort.
    return FALLBACK_VERSION


def main(argv: list[str] | None = None) -> int:
    args = list(sys.argv[1:] if argv is None else argv)
    if args == ["--stamp"]:
        version = stamp_bake_file()
        print(version)
        return 0
    if args in ([], ["--print"]):
        print(resolve_version())
        return 0
    print(
        "Usage: python -m farever_atlas.versioning [--print|--stamp]",
        file=sys.stderr,
    )
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
